name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_LOGIN_USER }}
        password: ${{ secrets.DOCKER_LOGIN_TOKEN }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.DOCKER_LOGIN_USER }}/pollitabot:${{ github.sha }}
        file: ./Dockerfile
        context: ./
              
    - name: Set up kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.CLUSTER_CONFIG }}" | base64 -d > $HOME/.kube/config

    - name: Update deployment image
      run: kubectl set image deployment/pollitabot-service pollitabot-service=${{ secrets.DOCKER_LOGIN_USER }}/pollitabot:${{ github.sha }}

